name: Generate Dashboard
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # Runs at 05:00 every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.40.3
        cache: true

    - run: pixi run render nightly
    - run: pixi run render latest

    - uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        branch: gh-pages
        folder: render
        single-commit: true

    # - name: Commit and push changes
    #   run: |
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     mv render/* .
    #     git checkout -b deploy-temp
    #     git add *.html favicon.ico plot.js style.css
    #     git commit -m "Deployed on $(date -u '+%Y-%m-%d %H:%M:%S')"
    #     git push -f origin deploy-temp:deploy
    #     git checkout main
    #     git branch -D deploy-temp
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
