name: Generate Dashboard
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"  # Runs at 05:00 every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        pixi-version: v0.44.0
        cache: true

    - run: pixi run render nightly
    - run: pixi run render latest

    - uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        branch: gh-pages
        folder: render
        single-commit: true
